#!/usr/bin/env bash
# Full deployment script: Infrastructure + API + Web
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"

# Configuration
RG_NAME="rg-rust-app"
ACR_NAME="acrrustapp"
LOCATION="eastus"
API_DNS="rust-api-demo"
WEB_DNS="rust-web-demo"
TAG="latest"

# Required: GEMINI_API_KEY must be set
if [ -z "${GEMINI_API_KEY:-}" ]; then
  echo "Error: GEMINI_API_KEY environment variable is required" >&2
  echo "Usage: GEMINI_API_KEY=<your-key> $0" >&2
  exit 1
fi

echo "============================================"
echo "  Rust Full-Stack Azure Deployment"
echo "============================================"
echo ""

cd "$REPO_ROOT"

# Step 1: Create Azure Resources
echo "[1/6] Creating Azure infrastructure..."
"$SCRIPT_DIR/create-azure-resources.sh" --rg "$RG_NAME" --location "$LOCATION" --acr "$ACR_NAME"
echo ""

# Step 2: Build and push API image
echo "[2/6] Building and pushing API image..."
"$SCRIPT_DIR/../rust-simple-rest-api/scripts/build-and-push-api.sh" --acr-name "$ACR_NAME" --tag "$TAG"
echo ""

# Step 3: Deploy API container
echo "[3/6] Deploying API container..."
"$SCRIPT_DIR/deploy-api-to-aci.sh" "$GEMINI_API_KEY"
echo ""

# Get API FQDN for config update
API_FQDN=$(az container show --resource-group "$RG_NAME" --name api-container --query ipAddress.fqdn -o tsv)
echo "API deployed at: http://${API_FQDN}:3000"
echo ""

# Step 4: Update frontend config with API URL
echo "[4/6] Updating frontend config with production API URL..."
CONFIG_FILE="$REPO_ROOT/rust-static-web-server/static/config.js"
cat > "$CONFIG_FILE" <<EOF
// Production configuration - auto-generated by deploy-all.sh
const API_URL = "http://${API_FQDN}:3000";
EOF
echo "Updated $CONFIG_FILE"
echo ""

# Step 5: Build and push Web image
echo "[5/6] Building and pushing Web image..."
"$SCRIPT_DIR/build-and-push-web.sh" --acr-name "$ACR_NAME" --tag "$TAG"
echo ""

# Step 6: Deploy Web container
echo "[6/6] Deploying Web container..."
"$SCRIPT_DIR/deploy-web-to-aci.sh" --rg "$RG_NAME" --dns "$WEB_DNS"
echo ""

# Final summary
WEB_FQDN=$(az container show --resource-group "$RG_NAME" --name web-container --query ipAddress.fqdn -o tsv)

echo "============================================"
echo "  Deployment Complete!"
echo "============================================"
echo ""
echo "  API URL: http://${API_FQDN}:3000"
echo "  Web URL: http://${WEB_FQDN}:8080"
echo ""
echo "  Test API: curl http://${API_FQDN}:3000/items"
echo "  Open Web: open http://${WEB_FQDN}:8080"
echo ""
echo "  To clean up all resources:"
echo "    az group delete --name $RG_NAME --yes --no-wait"
echo ""
